version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Anew_api_employee
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    container_name: golang_db
    ports:
      - "30306:3306"
    tty: true
  app:
    build:
      context: ./Go
    volumes:
      - .:/goWork/src/github.com/go_docker/Go"
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db